/* eslint-disable @next/next/no-page-custom-font */
import { useEffect, useState, useRef } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { gsap } from "gsap";
import { Tween } from "react-gsap";

import Logo from "../src/assets/svg/Logo";
import Navigation from "../src/components/Header/Navigation";
import Container from "../src/components/shared/Container";
import Fb from "../public/assets/fb.svg";
import tw from "../public/assets/twitter.svg";
import ig from "../public/assets/ig.svg";
import rocket from "../public/assets/rocket.png";
import comingsoon_second_img from "../public/assets/comingsoon_second_img.png";

export const ComingSoonNav = () => {
  return (
    <Tween
      from={{ delay: 0.1, height: "0%", opacity: 0 }}
      stagger={0.2}
      ease="elastic.out(0.1, 0.1)"
    >
      <div className="w-full shadow-md">
        <Container>
          <div className="flex flex-wrap items-center justify-between flex-1 p-2 md:py-2 lg:py-2">
            <div className="flex items-center lg:w-[60%]  xl:w-[70%] ">
              {/* logo and name */}
              <div className="flex items-center lg:w-[20%] xl:lg:w-[20%]">
                <Logo />
                <div className="mx-2 text-lg font-bold  md:text-lg lg:text-2xl font-poppins">
                  Lajeni
                </div>
              </div>

              {/* the nav bar */}
            </div>
          </div>
        </Container>
      </div>
    </Tween>
  );
};

const Home: NextPage = () => {
  // Creating the rocket reference
  const rocketRef = useRef<HTMLDivElement>(null);
  // Getting gsap selector
  const gsapSelector = gsap.utils.selector(rocketRef);

  const [days, setDays] = useState(0);
  const [hrs, setHrs] = useState(0);
  const [mins, setMins] = useState(0);
  const [sec, setSec] = useState(0);

  // Set the date we're counting down to
  let countDownDate = new Date("jun 5, 2022 12:00:00").getTime();
  const calculateCountDownInterval: NodeJS.Timer = setInterval(function () {
    // Get today's date and time
    let now = new Date().getTime();
    // Find the distance between now and the count down date
    let distance = countDownDate - now;

    // Time calculations for days, hours, minutes and seconds
    let days = Math.floor(distance / (1000 * 60 * 60 * 24));
    let hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    let minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    let seconds = Math.floor((distance % (1000 * 60)) / 1000);
    setDays(days);
    setHrs(hours);
    setMins(minutes);
    setSec(seconds);

    if (distance < 0) {
      clearInterval(calculateCountDownInterval);
    }
  }, 1000);

  useEffect(() => {
    gsap.to(gsapSelector(".rocket"), {
      yoyo: true,
      repeat: -1,
      delay: 1,
      y: 30,
      ease: "Power0.easeIn",
    });
  });

  useEffect(() => {
    return () => clearInterval(calculateCountDownInterval);
  });

  return (
    <div className="font-sans overflow-hidden">
      <Head>
        <title>Omega Dex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link key="google font" rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          key="google fonts dm"
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          key="dm sans google font"
          href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=IBM+Plex+Sans:wght@100;300;500&family=Island+Moments&family=Lobster&family=Neonderthaw&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="font-sans">
        <ComingSoonNav />
        {/* <Landingpage /> */}
        <main className="relative">
          {/* Banner back ground image */}
          <div className="flex font-sans h-[80vh] md:min-h-[476px] p-4  md:px-28 md:pt-28 flex-wrap bg-pattern bg-no-repeat bg-auto bg-center">
            {/* Write Up section */}
            <div className="w-full md:w-1/2 md:pt-0 pt-20">
              <p className="md:text-md  font-normal capitalize  text-light_blue">COMING SOON!!</p>
              <h1 className="text-4xl md:text-6xl font-bold py-2">Get Notified</h1>
              <h1 className="text-4xl md:text-6xl font-bold">When we launch</h1>
              {/* Form field for submitting email */}
              <form>
                <div className="h-[48px] md:w-10/12 gap-x-2 border-t border-l pl-1 border-b mt-10 flex justify-between items-center rounded-md">
                  <input
                    type="text"
                    className="h-full outline-none pl-4 w-9/12 rounded-md placeholder-neutral-300"
                    placeholder="Enter your Email address "
                  />
                  <button className="text-sm font-bold h-full px-3 w-3/12 text-white bg-primary rounded-md">
                    Notify Me
                  </button>
                </div>
              </form>

              {/* Countdown Boxes */}
              <section className="md:mt-8 mt-14 flex items-center space-x-5">
                <div
                  style={{
                    boxShadow: "0px 4px 0px #5510B4, 0px 16px 64px 5px rgba(31, 47, 70, 0.15)",
                  }}
                  className="h-[128px] p1 flex flex-col items-center justify-center rounded-md w-[116px] bg-white"
                >
                  <h5 className="text-4xl font-bold">{days}</h5>
                  <span className="font-[200] ">Days</span>
                </div>

                {/* Hour Box */}
                <div
                  style={{
                    boxShadow: "0px 4px 0px #5510B4, 0px 16px 64px 5px rgba(31, 47, 70, 0.15)",
                  }}
                  className="h-[128px] p1 flex flex-col items-center justify-center rounded-md w-[116px] bg-white"
                >
                  <h5 className="text-4xl font-bold">{hrs}</h5>
                  <span className="font-[200] ">Hours</span>
                </div>
                {/* Minute Box */}
                <div
                  style={{
                    boxShadow:
                      " 0px 4px 0px #CDB4DB, 0px 16px 64px -48px rgba(31, 47, 70, 0.15), 0px 16px 64px 2px rgba(31, 47, 70, 0.15)  ",
                  }}
                  className="h-[128px] p1 flex flex-col items-center justify-center rounded-md w-[116px] bg-white"
                >
                  <h5 className="text-4xl font-bold">{mins}</h5>
                  <span className="font-[200] ">Minutes</span>
                </div>
                {/* Seconds Box */}
                <div
                  style={{
                    boxShadow:
                      "0px 4px 0px #D6D8E0, 0px 16px 64px -48px rgba(31, 47, 70, 0.15), 0px 16px 64px 2px rgba(31, 47, 70, 0.15) ",
                  }}
                  className="h-[128px] p1 flex flex-col items-center justify-center shadow-md rounded-md w-[116px] bg-white"
                >
                  <h5 className="text-4xl font-bold">{sec}</h5>
                  <span className="font-[200] ">Seconds</span>
                </div>
              </section>
            </div>
            {/* Rocket Section */}
            <div className="w-full md:w-1/2 hidden md:flex justify-center items-center h-full">
              <span ref={rocketRef}>
                <Image
                  width="220"
                  height="450"
                  src={rocket}
                  alt="rocket image"
                  className="-z-10 rocket"
                />
              </span>
            </div>
          </div>
          <section className="bg-comingsoon z-10 flex justify-center items-center  bg-no-repeat bg-cover bg-blend-normal bg-top h-40 -mt-[6rem]">
            <Image src={comingsoon_second_img} alt="coming soon" className="mx-auto -z-20 -pt-20" />
          </section>
        </main>
        <footer className="bg-white border-t z-20 h-14">
          <Container>
            <div className="flex items-center flex-wrap h-14  justify-between">
              <span className="text-neutral-600 w-full md:w-6/12  md:text-left text-center text-sm">
                Copyright © {new Date().getFullYear()} Lajeni. All rights reserved
              </span>
              {/* Footer logos */}
              <div className="flex justify-center w-full md:justify-end items-center md:w-6/12 gap-x-5">
                <Image src={Fb} alt="facebbok" />
                <Image src={tw} alt="twitter" />
                <Image src={ig} alt="instagam" />
              </div>
            </div>
          </Container>
        </footer>
      </div>
    </div>
  );
};

export default Home;
