import React from "react";
import Head from "next/head";
import ForgotPasInputs from "../src/screens/ForgotPasInputs";

const forgetpassordinput = () => {
  return (
    <div>
      <Head>
        <title>Omega Dex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ForgotPasInputs />
    </div>
  );
};

export default forgetpassordinput;
