import type { NextPage } from "next";
import Head from "next/head";
import Signingpage from "src/screens/Signingpage";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Omega Dex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-poppins">
        <Signingpage />
      </div>
    </div>
  );
};

export default Home;
